import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Chris",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Amy",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "JW Blue Label",
      slug: "johnnie-walker-blue-label",
      label: "blue",
      image: "/images/blue.webp",
      price: 219.99,
      abv: 40,
      size: "750 ML",
      countInStock: 20,
      description:
        "Created from the rarest and most expensive whiskies in the world, individually numbered and produced in limited quantities. Johnnie Walker Blue has the authentic character and flavor of a traditional 19th century blend with traces of smoke, honey and spice on the silky finish.",
      taste: "Rich, Smoke, Honey, Spice, Long",
    },
    {
      name: "JW Red Label",
      slug: "johnnie-walker-red-label",
      label: "red",
      image: "/images/red.webp",
      price: 33.99,
      abv: 40,
      size: "1.75 L",
      countInStock: 20,
      description:
        "One of the world's best selling Scotch whiskies. Fresh and robust, this powerful combination of spicy, smoky malts and lingering, lighter grains is perfect for mixing. A distinctive strength of character and a fullness of flavor provides international appeal.",
      taste: "Light, Spice, Smoke, Oak, Balanced",
    },
    {
      name: "JW Green Label",
      slug: "johnnie-walker-green-label",
      label: "green",
      image: "/images/green.webp",
      price: 64.99,
      abv: 43,
      size: "750 ML",
      countInStock: 20,
      description:
        "A dynamic blend of Island and Speyside malts, each aged at least 15 years. The taste juxtaposes fresh fruit with wood smoke, pepper, deep vanilla and sandalwood. Perfectly balanced combination of only single malt whiskies that evokes the outdoors with its vibrant fresh flavor.",
      taste: "Rich, Wood, Fruit, Balanced",
    },
    {
      name: "JW Green 15 Year Old",
      slug: "johnnie-walker-green-label-15-year-old-750ml",
      label: "green",
      image: "/images/green.webp",
      price: 94.99,
      abv: 43,
      size: "750 ML",
      countInStock: 20,
      description:
        "A dynamic blend of Island and Speyside malts, each aged at least 15 years. The taste juxtaposes fresh fruit with wood smoke, pepper, deep vanilla and sandalwood. Perfectly balanced combination of only single malt whiskies that evokes the outdoors with its vibrant fresh flavor.",
      taste: "Rich, Wood, Fruit, Balanced",
    },
    {
      name: "Johnnie Walker Black Label",
      slug: "johnnie-walker-black-label",
      label: "black",
      image: "/images/black.webp",
      price: 59.99,
      abv: 40,
      size: "1.75 L",
      countInStock: 20,
      description:
        "The original Walker family blend, handcrafted from as many as 40 of the finest Scotch whiskies aged a minimum of 12 years, for a smooth and robust blend. Rich smoky malt, peat and sherry fruit character deliver a satisfyingly complex flavor on the long, lingering finish.",
      taste: "Rich, Smoke, Oak, Balanced",
    },
    {
      name: "Johnnie Walker Gold Label",
      slug: "johnnie-walker-gold-label",
      label: "gold",
      image: "/images/gold.webp",
      price: 64.99,
      abv: 40,
      size: "750 ML",
      countInStock: 20,
      description:
        "A skillful fusion of rare aged whiskies inspired by the notes originally kept by Sir Alexander Walker. Crafted from only a small number of Scotland's most renowned distilleries. Exceptionally smooth, creamy and delicate. Available in limited edition bottle. Perfect for gifts.",
      taste: "Medium, Tropical Fruit, Vanilla, Long",
    },
    {
      name: "Johnnie Walker 18 Years",
      slug: "johnnie-walker-18-years",
      label: "specialty",
      image: "/images/18years.webp",
      price: 64.99,
      abv: 40,
      size: "750 ML",
      countInStock: 20,
      description:
        "Introducing Johnnie Walker 18 Year Old - The Platinum Blend. Chosen from up to 18 unique Walker whiskies matured for a minimum of 18 years to create this blended scotch with a unique, rich, fruity-sweet character balanced with subtle smokiness and incredible smoothness.",
      taste:
        "Honeyed cereals, Cadbury's Fruit and Nut, distant bonfire smoke, clementine and spring blossom.",
    },
    {
      name: "Johnnie Walker King George V",
      slug: "johnnie-walker-king-george-v",
      label: "specialty",
      image: "/images/king.webp",
      price: 699.99,
      abv: 43,
      size: "750 ML",
      countInStock: 20,
      description:
        "Named for the king who awarded Johnnie Walker a royal warrant to supply his house with Scotch. Balance of peat, smoke, and lighter aromatic fruit flavors from a variety of oak casks. Extremely limited quantities, packaged in a crystal decanter with certificate of authenticity.",
      taste: "Rich, Peat, Smoke, Fruit, Balanced",
    },
    {
      name: "JW Blue W/ 2 Glasses",
      slug: "johnnie-walker-blue-w-2-glasses",
      label: "blue",
      image: "/images/jwblue2.webp",
      price: 189.99,
      abv: 40,
      size: "750 ML",
      countInStock: 20,
      description:
        "Born from the rarest and most expensive whiskies in the world, individually numbered and produced in limited quantities. Johnnie Walker Blue has the authentic character & flavor of a traditional 19th century blend with traces of smoke, honey & spice. A silky finish.",
      taste: "Rich, Smoke, Honey, Spice, Long",
    },
    {
      name: "200th Anniversary",
      slug: "johnnie-walker-blue-label-200th-anniversary-edition",
      label: "blue",
      image: "/images/jwblue3.webp",
      price: 3299.99,
      abv: 40,
      size: "750 ML",
      countInStock: 20,
      description:
        "The whisky in this special edition is a cask strength blend of Blue Label, so the full power of the flavors can be experienced. This exclusive Blue Label is contained in an exceptional Anniversary crystal decanter that has been especially created for Johnnie Walker.",
      taste: "Rich, Smoke, Oak, Vanilla, Balanced",
    },
    {
      name: "JW Swing",
      slug: "johnnie-walker-swing",
      label: "specialty",
      image: "/images/jwswing.webp",
      price: 66.99,
      abv: 40,
      size: "750 ML",
      countInStock: 20,
      description:
        "Originally designed to counteract unruly ocean waves while aboard the great luxury steamships. Today, the distinctive bottle contains a blend of Speyside, Highlands and Islay malts for richness, spice and weight, with a touch of sweetness on the elegant finish.",
      taste: "Rich, Spice, Sweet, Balanced",
    },
    {
      name: "JW Red Label",
      slug: "johnnie-walker-red-label-2",
      label: "red",
      image: "/images/red2.webp",
      price: 9.97,
      abv: 40,
      size: "50 ML",
      countInStock: 20,
      description:
        "One of the world's best selling Scotch whiskies. Fresh and robust, this powerful combination of spicy, smoky malts and lingering, lighter grains is perfect for mixing. A distinctive strength of character and a fullness of flavor provides international appeal.",
      taste: "Light, Spice, Smoke, Oak, Balanced",
    },
    {
      name: "JW Double Black",
      slug: "johnnie-walker-double-black",
      label: "black",
      image: "/images/black2.webp",
      price: 9.97,
      abv: 40,
      size: "750 ML",
      countInStock: 20,
      description:
        "Hand selected whiskies defined by hints of smoldering charcoal, and burnt timber matured in deep-charred oak casks. A smoky intense experience with a smoky nose, unmistakable spice and slight notes of dark fruit followed by a lingering smoky finish. Enjoy neat.",
      taste: "Rich, Smoke, Oak, Long",
    },
    {
      name: "High Rye",
      slug: "johnnie-walker-high-rye-blended-scotch-whisky",
      label: "green",
      image: "/images/green3.webp",
      price: 9.97,
      abv: 45,
      size: "750 ML",
      countInStock: 20,
      description:
        "Hand selected whiskies defined by hints of smoldering charcoal, and burnt timber matured in deep-charred oak casks. A smoky intense experience with a smoky nose, unmistakable spice and slight notes of dark fruit followed by a lingering smoky finish. Enjoy neat.",
      taste: "Rich, Smoke, Oak, Long",
    },
    {
      name: "JW Black Label",
      slug: "johnnie-walker-black-label-2",
      label: "black",
      image: "/images/black3.webp",
      price: 5.99,
      abv: 45,
      size: "50 ML",
      countInStock: 20,
      description:
        "The original Walker family blend, handcrafted from as many as 40 of the finest Scotch whiskies aged a minimum of 12 years, for a smooth and robust blend. Rich smoky malt, peat and sherry fruit character deliver a satisfyingly complex flavor on the long, lingering finish.",
      taste: "Rich, Smoke, Oak, Balanced",
    },
    {
      name: "JW Red Label",
      slug: "johnnie-walker-red-label-3",
      label: "red",
      image: "/images/red3.webp",
      price: 5.99,
      abv: 45,
      size: "50 ML",
      countInStock: 20,
      description:
        "One of the world's best selling Scotch whiskies. Fresh and robust, this powerful combination of spicy, smoky malts and lingering, lighter grains is perfect for mixing. A distinctive strength of character and a fullness of flavor provides international appeal.",
      taste: "Light, Spice, Smoke, Oak, Balanced",
    },
    {
      name: "JW Black Gift",
      slug: "johnnie-walker-red-label-4",
      label: "red",
      image: "/images/black4.webp",
      price: 36.99,
      abv: 45,
      size: "50 ML",
      countInStock: 20,
      description:
        "Johnnie Walker Black is a true icon, recognized as the benchmark for all other deluxe blends. Created using only whiskies aged for a minimum of 12 years from the four corners of Scotland, Johnnie Walker Black has an unmistakably smooth, deep character.",
      taste: "Light, Spice, Smoke, Oak, Balanced",
    },
    {
      name: "Johnnie White Walker",
      slug: "johnnie-white-walker",
      label: "specialty",
      image: "/images/white.png",
      price: 36.99,
      abv: 45,
      size: "50 ML",
      countInStock: 20,
      description:
        "Game of Thrones & Johnnie Walker have teamed up to release White Walker By Johnnie Walker. This latest release comes complete with cold-reactive packaging that causes new artwork to appear on the bottle if it is chilled in the freezer as well as the show's most famous quote, Winter is here, along the side. Prepare for the return of Game Of Thrones with a bottle of Johnnie Walker's White Walker!",
      taste: "Light, Spice, Smoke, Oak, Balanced",
    },
    {
      name: "200th Anniversary",
      slug: "johnnie-walker-blue-label 200th-anniversary-edition",
      label: "specialty",
      image: "/images/blue200.jpg",
      price: 5499.99,
      abv: 45,
      size: "50 ML",
      countInStock: 20,
      description:
        "Johnnie Walker Blue Label 200th Anniversary Edition celebrates John and Alexander Walker’s pioneering spirit and groundbreaking style. This special limited edition has been created to commemorate the anniversary of John Walker’s birthday, on 25th July 1805. As a cask strength blend of Blue Label, the full power of the flavours can be experienced. This exclusive Johnnie Walker Blue Label is bottled in a special anniversary crystal decanter that has been specially created for Johnnie Walker by Baccarat.",
      taste: "Rich, Smoke, Oak, Vanilla, Balanced",
    },
    {
      name: "Bicentenary Blend",
      slug: "john-walker-and-sons-bicentenary-blend",
      label: "specialty",
      image: "/images/bic.webp",
      price: 1499.99,
      abv: 45,
      size: "50 ML",
      countInStock: 20,
      description:
        "Master Blender Jim Beveridge and his small team of expert whisky makers have drawn inspiration from the thrilling flavors listed on an original inventory from John Walker’s store. Using this as a window into the world where John started, they have meticulously crafted a complex whisky with rich layers that re-imagines the kaleidoscope of exotic flavors that shaped our founder’s imagination.",
      taste: "A sweet spice lingers as the door closes behibd you.",
    },
    {
      name: "Jane Walker",
      slug: "johnnie-walker-black-label-the-jane-walker-edition",
      label: "specialty",
      image: "/images/jane.webp",
      price: 1499.99,
      abv: 45,
      size: "50 ML",
      countInStock: 20,
      description:
        "Master Blender Jim Beveridge and his small team of expert whisky makers have drawn inspiration from the thrilling flavors listed on an original inventory from John Walker’s store. Using this as a window into the world where John started, they have meticulously crafted a complex whisky with rich layers that re-imagines the kaleidoscope of exotic flavors that shaped our founder’s imagination.",
      taste: "A sweet spice lingers as the door closes behibd you.",
    },
  ],
};

export default data;
