import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Chris",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Amy",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Johnnie Walker Blue Label",
      slug: "johnnie-walker-blue-label",
      label: "blue",
      image: "/images/blue.webp",
      price: 219.99,
      size: "750 ML",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
    {
      name: "Johnnie Walker Red Label",
      slug: "johnnie-walker-red-label",
      label: "red",
      image: "/images/red.webp",
      price: 33.99,
      size: "1.75 L",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
    {
      name: "Johnnie Walker Green Label",
      slug: "johnnie-walker-green-label",
      label: "green",
      image: "/images/green.webp",
      price: 64.99,
      size: "750 ML",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
    {
      name: "Johnnie Walker Green Label2",
      slug: "johnnie-walker-green-label2",
      label: "green",
      image: "/images/green.webp",
      price: 64.99,
      size: "750 ML",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
    {
      name: "Johnnie Walker Green Label3",
      slug: "johnnie-walker-green-label3",
      label: "green",
      image: "/images/green.webp",
      price: 64.99,
      size: "750 ML",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
    {
      name: "Johnnie Walker Black Label",
      slug: "johnnie-walker-black-label",
      label: "black",
      image: "/images/black.webp",
      price: 59.99,
      size: "1.75 L",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
    {
      name: "Johnnie Walker Gold Label",
      slug: "johnnie-walker-gold-label",
      label: "gold",
      image: "/images/gold.webp",
      price: 64.99,
      size: "750 ML",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
    {
      name: "Johnnie Walker 18 Years",
      slug: "johnnie-walker-18-years",
      label: "specialty",
      image: "/images/18years.webp",
      price: 64.99,
      size: "750 ML",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
    {
      name: "Johnnie Walker King George V",
      slug: "johnnie-walker-king-george-v",
      label: "specialty",
      image: "/images/king.webp",
      price: 699.99,
      size: "750 ML",
      countInStock: 20,
      description: "A popular Whiskey.",
    },
  ],
};

export default data;
