import db from '../utils/db';
import { Store } from '../utils/Store';
import axios from 'axios'
import { toast } from "react-toastify";
import { useContext } from "react";
import Hero from "../components/hero/Hero";
import Head from "next/head";
import PopProducts from "../components/popProducts/PopProducts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <PopProducts />
    </>
  );
}


// export async function getServerSideProps() {
//   await db.connect();
//   const products = await Product.find()
// }